experiment_name: "gemini_flash_lite_medqa_step_250"
model_name: "gemini-3.1-flash-lite"
override_model: true
dataset_name: "FLD"
max_workers: 20

run_tasks: ['main_experiment']

main_experiment:
  datasets:
    - "MedQA-Step1"
    - "MedQA-Step2_3"
  sample_limits:
    MedQA-Step1: 250
    MedQA-Step2_3: 250
  run_s5_rerun: true
  results_dir: "results/ab_gemini_medqa250"
paths:
  raw_dataset_template: "dataset/{dataset_name}.json"
